server:
  port: ${config.port:11000}

spring:
  application:
    name: org-limingnihao-server-eureka

eureka:
  instance:
    hostname: ${config.address:127.0.0.1}
    preferIpAddress: true
    prefer-ip-address: true

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/